name: Tests unitaires de l'app

on:
  push
  # pull-request:
  #   types:
  #     - closed
  #   branches:
  #     - master

env:
  APP_VERSION: "1.0.0"

jobs:
  Tests-app:
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Récupération du repo
        uses: actions/checkout@v3
      - 
          name: je liste le contenu du repo
          run: ls -alF
      # - 
      #   name: Je créée un ticket en cas d'échec
      #   if: failure()
      #   uses: actions-ecosystem/action-create-issue@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     title: Echec test unitaire
      #     body: |
      #       ## A faire au plus vite
      #       - [ ] Revoir le code
      #       - [ ] Revoir le process 

  Build-app:
    runs-on: ubuntu-latest
    needs: Tests-app
    steps: 
      - 
        name: Récupération du repo
        uses: actions/checkout@v3
      
      - name: Installation Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - 
        name: Run PyTest
        run: pytest
      # - 
      #   name: Récupération des logs
      #   uses: actions/upload-artifacts@v3
      #   with:
      #     name: mon-reports.txt
      #     path: ./reports.txt